#!/bin/bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Construct the remote destination path (user's home directory)
remote_path="~/"

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:$remote_path"

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
